#!/usr/bin/env bash
# Prints the Airflow UI credentials generated by the simple auth manager.
#
#   bash scripts/creds.sh      (or just: airflow-creds)
#
# Airflow generates a fresh random password for each user on every startup and
# writes it to a JSON file. That file is authoritative - edit it and restart to
# pin a password of your own.
set -euo pipefail

DEFAULT_HOME="${AIRFLOW_HOME:-$HOME/airflow}"
FILE="${AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE:-${DEFAULT_HOME}/simple_auth_manager_passwords.json.generated}"

if [ ! -f "$FILE" ]; then
  cat <<EOF
No password file found at:
  $FILE

Airflow writes it on first start. Run this in another terminal:

  airflow standalone

then re-run this script.
EOF
  exit 1
fi

echo "Airflow UI    : Ports tab -> click the globe icon on port 8080"
echo "Password file : $FILE"
echo
echo "  USER            PASSWORD"
echo "  ----            --------"

python - "$FILE" <<'PY'
import json
import sys

with open(sys.argv[1]) as fh:
    users = json.load(fh)

width = max((len(u) for u in users), default=8)
for user, password in users.items():
    print(f"  {user:<{width}}    {password}")
PY

cat <<'EOF'

To pin a password instead of hunting for a new one each restart:

  echo '{"admin": "admin"}' > "$AIRFLOW_HOME/simple_auth_manager_passwords.json.generated"

then Ctrl+C and re-run `airflow standalone`.
EOF
